# Generated by Django 6.0.3 on 2026-04-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_phon',
            new_name='customer_phone',
        ),
    ]
